name: Pipeline
on:
    workflow_dispatch:
    push:
        - dev
        - main

jobs:
    Build-Test:
        runs-on: ubuntu-latest
        environment: ${{github.ref_name == 'dev' && 'development' || 'production'}}
        defaults:
            run:
                shell: bash
        
        steps:
            - name: 'Checkout'
              uses: actions/checkout@v6
            
            - name: Get or create an OCIR Repository
              uses: oracle-actions/get-ocir-repository@v1.3.0
              id: get-ocir-repository
              with:
                name: oraclelinux
                compartment: ${{ secrets.OCI_COMPARTMENT_OCID }}

            - name: 'Log in to OCIR'
              uses: oracle-actions/login-ocir@v1.3.0
              id: login-ocir
              with:
                auth_token: ${{ secrets.OCI_AUTH_TOKEN }}

            - name: 'Build and Push Docker Image'
              run: |
                docker build -t ${{ secrets.OCI_REGION_KEY }}.ocir.io/${{ secrets.OCI_NAMESPACE }}/intelitech-front:${{ github.sha }} .
                docker push ${{ secrets.OCI_REGION_KEY }}.ocir.io/${{ secrets.OCI_NAMESPACE }}/intelitech-front:${{ github.sha }}