name: Pipeline

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - dev

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    environment: ${{ github.ref_name == 'dev' && 'development' || 'production' }}
    defaults:
      run:
        shell: bash
    env: 
      OCI_CLI_USER: ${{ secrets.OCI_USERNAME }}
      OCI_CLI_TENANCY: ${{ secrets.OCI_NAMESPACE }}
      OCI_CLI_REGION: ${{ secrets.OCI_REGION_KEY }}
      OCI_CLI_FINGERPRINT: ${{ secrets.OCI_FINGERPRINT}}
      OCI_AUTH_TOKEN: ${{secrets.OCI_AUTH_TOKEN}}
      OCI_NAMESPACE_NAME: ${{ secrets.OCI_NAMESPACE_NAME }}
      VM_PUBLIC_IP: ${{ vars.VM_PUBLIC_IP }}

    steps:
      # Checkout source code
      - name: 'Checkout'
        uses: actions/checkout@v6
        
      - name: Log into OCIR
        run: |
          echo "${OCI_AUTH_TOKEN}" | docker login ${OCI_CLI_REGION}.ocir.io -u "${OCI_CLI_TENANCY}/${OCI_CLI_USER}" --password-stdin

      - name: 'Build and Push Docker Image'
        run: |
          docker build -t ${OCI_CLI_REGION}.ocir.io/${OCI_CLI_TENANCY}/${OCI_NAMESPACE_NAME}/intelitech-front:${{ github.sha }} .
          docker push ${OCI_CLI_REGION}.ocir.io/${OCI_CLI_TENANCY}/${OCI_NAMESPACE_NAME}/intelitech-front:${{ github.sha }}
      - name: SSH into OCI VM
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}   # sua chave privada
        run: |
          echo "$SSH_PRIVATE_KEY" > private_key
          chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key opc@$VM_PUBLIC_IP <<'EOF'
            # Comandos a serem rodados dentro da VM
            docker pull ${OCI_CLI_REGION}.ocir.io/${OCI_CLI_TENANCY}/${OCI_NAMESPACE_NAME}/intelitech-front:${{ github.sha }}
            docker stop intelitech-front || true
            docker rm intelitech-front || true
            docker run -d --name intelitech-front -p 80:80 ${OCI_CLI_REGION}.ocir.io/${OCI_CLI_TENANCY}/${OCI_NAMESPACE_NAME}/intelitech-front:${{ github.sha }}
          EOF
          # Remove a chave privada do runner
          rm -f private_key